-- MySQL Script generated by MySQL Workbench
-- Mon May 24 10:29:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_grupos` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tema` VARCHAR(45) NOT NULL,
  `fk_usuario_criador` INT NOT NULL,
  PRIMARY KEY (`id_grupo`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_tb_grupos_tb_usuarios_idx` (`fk_usuario_criador` ASC) VISIBLE,
  CONSTRAINT `fk_tb_grupos_tb_usuarios`
    FOREIGN KEY (`fk_usuario_criador`)
    REFERENCES `mydb`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_postagens` (
  `id_postagem` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `url_imagem` VARCHAR(255) NULL,
  `fk_grupo_criador` INT NOT NULL,
  `fk_usuario_criador` INT NOT NULL,
  PRIMARY KEY (`id_postagem`),
  INDEX `fk_tb_postagens_tb_grupos1_idx` (`fk_grupo_criador` ASC) VISIBLE,
  INDEX `fk_tb_postagens_tb_usuarios1_idx` (`fk_usuario_criador` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_grupos1`
    FOREIGN KEY (`fk_grupo_criador`)
    REFERENCES `mydb`.`tb_grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagens_tb_usuarios1`
    FOREIGN KEY (`fk_usuario_criador`)
    REFERENCES `mydb`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_inscritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_inscritos` (
  `tb_usuarios_id_usuario` INT NOT NULL,
  `tb_grupos_id_grupo` INT NOT NULL,
  PRIMARY KEY (`tb_usuarios_id_usuario`, `tb_grupos_id_grupo`),
  INDEX `fk_tb_usuarios_has_tb_grupos_tb_grupos1_idx` (`tb_grupos_id_grupo` ASC) VISIBLE,
  INDEX `fk_tb_usuarios_has_tb_grupos_tb_usuarios1_idx` (`tb_usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuarios_has_tb_grupos_tb_usuarios1`
    FOREIGN KEY (`tb_usuarios_id_usuario`)
    REFERENCES `mydb`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuarios_has_tb_grupos_tb_grupos1`
    FOREIGN KEY (`tb_grupos_id_grupo`)
    REFERENCES `mydb`.`tb_grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_comentarios` (
  `id_comentarios` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(255) NOT NULL,
  `fk_postagem` INT NOT NULL,
  PRIMARY KEY (`id_comentarios`),
  INDEX `fk_tb_comentarios_tb_postagens1_idx` (`fk_postagem` ASC) VISIBLE,
  CONSTRAINT `fk_tb_comentarios_tb_postagens1`
    FOREIGN KEY (`fk_postagem`)
    REFERENCES `mydb`.`tb_postagens` (`id_postagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
